[WIP] public api
SmartCityProjectGroup/SC_Microservice1 pull request #1
Opened 2022-05-05 18:49 UTC by tristankechlo

### Erledigt
 - MySQL Verbindung
 - RabbitMQ Events verschicken
 - MVP: öffentiche Routen für
     - Informationen zu einem Bürger
     - ob der Bürger einen Sachkundenachweis für Hundehalter hat
     - Informationen zu den Kindern eines Bürgers
 
### Noch zu erledigen
 - Tests
 - Datenbanktyp für die BürgerID anpassen (String -> Integer)

2022-05-07 17:52 UTC, tristankechlo commented
- Datenbank wurde angepasst
 - Tests wurden erstellt
 - inwieweit das Buildscript angepasst werden muss, weiß ich nicht genau

2022-05-09 10:29 UTC, SgtEpic requested changes
Sieht soweit ganz gut aus. Ein paar Kleinigkeiten sind noch hier und da:

Mir ist aufgefallen, dass einige Funktionen für die SQL Anfragen noch nicht vollständig implementiert wurden. Die müssten implementiert werden, damit die ganze Sache abgeschlossen ist, oder du sagst, dass das soweit "nur" der Stand für den MVP wäre. Dann müsstet du das natürlich später in einem anderen Pull Request implementieren. 
Wenns die MVP Variante sein soll, wäre es ganz gut, wenn das im Titel des Pull Requests irgendwie sichtbar wird, sodass man das auch sofort sehen kann, dass das noch nicht die finale Version ist.

In den Fällen, wo du eigentlich bei SmartAuth nach der Berechtigung des Clients fragen würdest, ist es natürlich ärgerlich, dass SmartAuth noch nicht soweit ist. Ich würde vorschlagen, dass an allen Stellen, wo du nach Berechtigungen fragst, einen Funktionsaufruf machst, der sich um den Part kümmert. Die Funktion wäre dann erstmal nur ein Prototyp, der z.B. immer true zurückgibt, aber so musst du dich nicht an alle Stellen erinnern, wo du nach Berechtigungen fragst, sondern kannst das alles in einem Rutsch ändern.

Bei den Events wird im Routing Key noch der Name des Events inkludiert. Wir können im nächsten Meeting besprechen, ob wir die Routing Keys nach diesem Schema ändern wollen, aber für jetzt sind die Eventnamen nicht Teil des Keys und so gibt es auch Routingprobleme, wenn die Eventnamen mit in dem Key sind.

Als Letztes nur was Kleines: In der Spezifikation taucht bisher die Anfrage zum Erstellen eines Bürgers nicht auf. Das muss noch ergänzt werden. 
Das Event "Neuer Bürger" heißt in der Spezifikation "Neuer Bürger gemeldet" und in der Implementierung ist das zu "Neuer Bürger" geworden. Auch wenn die Anderen sich wahrscheinlich nicht auf den Namen verlassen, wäre es trotzdem gut, wenn Spezifikation und Implementierung übereinstimmen.

Der Rest sieht super aus. Die Tests sind umfangreich und es wird überall auf alle möglichen Fehler geprüft. So muss das.

2022-05-09 11:03 UTC, tristankechlo commented
- Die Route zum Erstellen eines Bürgers soll keine sein die die anderen Microservices nutzen sollen, deshalb ist diese nicht in der Spezifikation
 - Sollen ***alle* Events dann den Routingkey `public.buergerbuero` haben?

2022-05-09 11:40 UTC, SgtEpic commented
1. Die Spezifikation soll alle Routen enthalten, egal ob die nur von dir oder auch von anderen genutzt werden. 
2. Genau für alle Events ist der Routing Key der gleiche `public.buergerbuero`

2022-05-14 12:14 UTC, tristankechlo commented
1. RoutingKeys der Events wurden angepasst
2. Datenbankaufrufe sind nun implementiert
3. Prototyp für die Kommunikation mit SmartAuth wurde erstellt
4. Spezifikation wurde um den API-Aufruf erweitert

2022-05-16 10:05 UTC, merged